const FONT_SIZE_DESKTOP_HEADING = "3rem";
const FONT_SIZE_MOBILE_HEADING = "2rem";
const FONT_SIZE_DESKTOP_TITLE = "2rem";
const FONT_SIZE_MOBILE_TITLE = "1.5rem";
const FONT_SIZE_DESKTOP_BODY = "1rem";
const FONT_SIZE_MOBILE_BODY = "1rem";

export {
    FONT_SIZE_DESKTOP_HEADING,
    FONT_SIZE_DESKTOP_BODY,
    FONT_SIZE_MOBILE_BODY,
    FONT_SIZE_MOBILE_HEADING,
    FONT_SIZE_DESKTOP_TITLE,
    FONT_SIZE_MOBILE_TITLE,
};
